# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/batman/Desktop/216_assignments/main_project/main_project.cache/wt [current_project]
set_property parent.project_path /home/batman/Desktop/216_assignments/main_project/main_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/batman/216_assignments/main_project/main_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/ip/BRAM2_blk_mem_gen_0_0/data.coe
read_vhdl -library xil_defaultlib {
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/shifter.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/Register_File.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/proc_mem_path.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/multiplier.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/mem_proc_path.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/alu.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/hdl/BRAM2_wrapper.vhd
  /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/new/datapath.vhd
}
add_files /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/BRAM2.bd
set_property used_in_implementation false [get_files -all /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/ip/BRAM2_blk_mem_gen_0_0/BRAM2_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/BRAM2_ooc.xdc]
set_property is_locked true [get_files /home/batman/Desktop/216_assignments/main_project/main_project.srcs/sources_1/bd/BRAM2/BRAM2.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top datapath -part xc7a35tcpg236-1


write_checkpoint -force -noxdef datapath.dcp

catch { report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb }
